[core]
order = 10000

[package]
# Semantic Versioning is used: https://semver.org/
version = "2.22.12"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "TM Digital Robot"
description = "TM Digital Robot"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Simulation"

# Keywords for the extension
keywords = ["kit", "example"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import tmrobot.digital_robot".
[[python.module]]
name = "tmrobot.digital_robot"

# https://docs.omniverse.nvidia.com/kit/docs/omni.kit.pipapi/latest/Overview.html
# [python.pipapi]
# requirements = ["grpcio==1.68.1","grpcio-tools", "protobuf", "numpy", "python-dotenv"]
# use_online_index = true
# ignore_import_check = false
# extra_args = ["--no-cache-dir"]


[settings]
# log.level = "debug"
# log.fileLogLevel = "debug"
# log.outputStreamLevel = "debug"
log.level = "info"
log.fileLogLevel = "info"
log.outputStreamLevel = "info"

# Hiding Known Warning: [Warning] [omni.hydra] Mesh '/World/AMR_Robot/Robot01/tm12s/body/link_1/visuals' has corrupted data in primvar
log.channels."omni.hydra" = "error"

# Hiding Known Warning: [Warning] [omni.usd] Warning: in SdfPath at line 81 of /builds/omniverse/usd-ci/USD/pxr/usd/sdf/path.cpp -- Ill-formed SdfPath <>: syntax error
log.channels."omni.usd" = "error"

# Hiding Known Warning: [Warning] Reached maximum folder subscribers count in extension folder
log.channels."omni.ext.plugin" = "error"

# Hiding Know Warning: [Warning] [omni.physx.plugin] The rigid body at /World/station_server_flying_trigger/stand_base/Robot01/tm12/body/base has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass, small sphere approximated inertia was used. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for.
log.channels."omni.physx.plugin" = "error"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test", # UI testing extension
]

